### PR TITLE
Typescript

### PR DESCRIPTION
**Pull request by mdnihal5**

### CODE REVIEW

**Comment by cneuralnetwork** [comment]
Heyy
Could you add the file as mentioned in the README

a folder named typescript and the file should be in it named nn.ts

**Comment by mdnihal5** [comment]
I did the same thing ig ?
Screenshot_2024-10-02-14-44-33-881-edit_com android chrome

**Comment by mdnihal5** [comment]
Hello
I thing i did the same thing here 
image
Screenshot from 2024-10-02 14-49-12

it is in the branch typescript ( i created a seperate branch )

**Comment by cneuralnetwork** [comment]
Okayy Mergedd

**Pull request merged**
